# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\机创电控\app\ui\kimi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(938, 602)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 20, 921, 581))
        self.frame.setStyleSheet("#frame{\n"
"border-radius:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(840, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/winfo-icon-最小化_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 10, 41, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/关闭(close)_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(290, 60, 311, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/截图20250715121425.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 420, 591, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/截图20250715163726.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 160, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/截图20250715163942.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(210, 150, 521, 261))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/截图20250715164826.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.answer = QtWidgets.QTextEdit(self.frame)
        self.answer.setGeometry(QtCore.QRect(230, 180, 481, 211))
        self.answer.setStyleSheet("border:none;")
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.question = QtWidgets.QTextEdit(self.frame)
        self.question.setGeometry(QtCore.QRect(200, 450, 361, 81))
        self.question.setStyleSheet("border:none;")
        self.question.setObjectName("question")
        self.send = QtWidgets.QPushButton(self.frame)
        self.send.setGeometry(QtCore.QRect(700, 490, 41, 41))
        self.send.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.send.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/截图20250715165353.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send.setIcon(icon2)
        self.send.setIconSize(QtCore.QSize(40, 40))
        self.send.setObjectName("send")
        self.record = QtWidgets.QPushButton(self.frame)
        self.record.setGeometry(QtCore.QRect(200, 480, 41, 71))
        self.record.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.record.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/录音结束 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.record.setIcon(icon3)
        self.record.setIconSize(QtCore.QSize(33, 33))
        self.record.setObjectName("record")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
