# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\机创电控\app\ui\mu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 535)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 541, 511))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(255, 238, 226);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_browse = QtWidgets.QPushButton(self.frame)
        self.btn_browse.setGeometry(QtCore.QRect(40, 30, 93, 71))
        self.btn_browse.setStyleSheet("QPushButton{\n"
"    background-color: rgb(165, 149, 143);\n"
"    border:none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"}")
        self.btn_browse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/预选歌曲.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_browse.setIcon(icon)
        self.btn_browse.setIconSize(QtCore.QSize(65, 65))
        self.btn_browse.setObjectName("btn_browse")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 10, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/winfo-icon-最小化_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 0, 41, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/关闭(close)_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_cover = QtWidgets.QLabel(self.frame)
        self.label_cover.setGeometry(QtCore.QRect(220, 60, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cover.setFont(font)
        self.label_cover.setStyleSheet("background-color: rgb(255, 247, 224);")
        self.label_cover.setText("")
        self.label_cover.setObjectName("label_cover")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(440, 50, 31, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/文件_ 文件_ 报告_ 搜索引擎优化图标(Document__爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 60, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 401, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/视频播放.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.slider_progress = QtWidgets.QSlider(self.frame)
        self.slider_progress.setGeometry(QtCore.QRect(110, 400, 291, 22))
        self.slider_progress.setStyleSheet("")
        self.slider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_progress.setObjectName("slider_progress")
        self.label_current = QtWidgets.QLabel(self.frame)
        self.label_current.setGeometry(QtCore.QRect(20, 400, 72, 15))
        self.label_current.setText("")
        self.label_current.setObjectName("label_current")
        self.label_total = QtWidgets.QLabel(self.frame)
        self.label_total.setGeometry(QtCore.QRect(440, 400, 72, 15))
        self.label_total.setText("")
        self.label_total.setObjectName("label_total")
        self.btn_play_pause = QtWidgets.QPushButton(self.frame)
        self.btn_play_pause.setGeometry(QtCore.QRect(210, 420, 101, 41))
        self.btn_play_pause.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"border:none;\n"
"border-radius:10;")
        self.btn_play_pause.setText("")
        self.btn_play_pause.setObjectName("btn_play_pause")
        self.btn_reset = QtWidgets.QPushButton(self.frame)
        self.btn_reset.setGeometry(QtCore.QRect(150, 430, 31, 31))
        self.btn_reset.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.btn_reset.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/复原.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reset.setIcon(icon4)
        self.btn_reset.setIconSize(QtCore.QSize(30, 30))
        self.btn_reset.setObjectName("btn_reset")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_2.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "文件名："))

