# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\机创电控\app\ui\seg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(940, 728)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(50, 70, 801, 571))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("#frame{\n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video = QtWidgets.QLabel(self.frame)
        self.video.setGeometry(QtCore.QRect(50, 180, 311, 281))
        self.video.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.video.setText("")
        self.video.setObjectName("video")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(610, 60, 31, 31))
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setPixmap(QtGui.QPixmap("images/坐标02 (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(730, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/winfo-icon-最小化_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 10, 41, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/关闭(close)_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(640, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(80, 470, 101, 61))
        self.start.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.start.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/录音结束.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon2)
        self.start.setIconSize(QtCore.QSize(40, 40))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(200, 460, 101, 81))
        self.stop.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.stop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/结束按钮.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon3)
        self.stop.setIconSize(QtCore.QSize(50, 50))
        self.stop.setObjectName("stop")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(380, 60, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/特征提取.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(420, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.image = QtWidgets.QLabel(self.frame)
        self.image.setGeometry(QtCore.QRect(400, 290, 341, 231))
        self.image.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(50, 70, 71, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/deeplab.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(140, 70, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"color: rgb(48, 48, 48);\n"
"font: italic 25pt \"Arial Narrow\";")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(440, 240, 41, 41))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/ivpd 智能视觉生产.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(490, 240, 181, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.feature = QtWidgets.QTextEdit(self.frame)
        self.feature.setGeometry(QtCore.QRect(390, 110, 161, 111))
        self.feature.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.feature.setObjectName("feature")
        self.axis = QtWidgets.QTextEdit(self.frame)
        self.axis.setGeometry(QtCore.QRect(610, 110, 161, 111))
        self.axis.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.axis.setObjectName("axis")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.showMinimized) # type: ignore
        self.pushButton_4.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "坐标提取"))
        self.label_7.setText(_translate("Form", "特征提取"))
        self.label_11.setText(_translate("Form", "DeeplabV3+"))
        self.label_12.setText(_translate("Form", "实例分割结果"))
